### ISSUE TITLE
Cpp - Wtp interfaces connection

### ISSUE THREAD

**Issue by Giwrgosyea** [5g-empower/empower-lvnf-agent#2]
I kind dont understand the deployment of empower ( cpp-wtp connection).
You mention that eth0 of both 2 wtps must be connected to the cpp. 
But if eth1 of both wtps is not connected with the switch , the wtps dont connect to the controller.
I followed your instructions as you describe in the wiki .

Beside that connecting eth1 of both wtps to the switch and the eth0 to cpp , they connect with the controller.The wtps emmit wifi  but when if i try to connect a client to the empower network, the client does not get IP.

**Comment by rriggio** [comment]
I said eth0 because in my case (alix wtps) the eth0 is the WAN interface
which is bridged
with the OVS. If in you case it is the eth1 to be bridged with the ovs then
you must connect
the wtps to the cpps using the eth1.

Basically the port used to delivere connectivity to the WTP must be
connected to the CPP
and everything should be a single L2 domain.

R.

**Comment by Giwrgosyea** [comment]
I followed exactly your instructions in the wiki.The config files of both wtps and cpp are exactly the same with yours (but obviously with my custom IPs).But if I connect  only the eth0 with the cpp ,the wtp does not connect to the controller. So whats the point of eth1 in configuration file of wtp ?

**Comment by rriggio** [comment]
It is an ALIX WTP right?

The eth1 is running a local dhcp server. Basically it allows you to connect
to the eth1 port with a laptop
for example and to login in the wtp for management purposes. It is not
really needed for empower, so
you can also remove it.

Can the WTP ping the ip of the controller? You need L3 connectivity between
wtp and controller in order
for this to work. Also this setup assumes that there is a DHCP server on
the network where WTP and
CPPs are located.

R.

**Comment by Giwrgosyea** [comment]
Yes its a soekris net5501.

If I remove eth1 from the wtp it dont connect to the controller and cant ping.
The only way for me to connect  WTP with the controller is to connect eth1 of wtp with my local switch  and eth0 with the cpp , if I remove the cpp from my deployment in order to connect the wtp with the controller both eth1 and eth0 must be connected with my local switch.

**Comment by rriggio** [comment]
Hi,

check this for example:

https://github.com/5g-empower/5g-empower.github.io/wiki/Network-setup#wtpscpps

Is this the configuration you have in your lab?

That is the setup I have in my lab. The two wtps in the picture are
connected from their eth0 port to ports eth1 and eth2 of the CPP.

Also ports eth1,2,3 of the CPP are bridged together in an OVS bridge, while
eth0 of the CPP is not bridged with the other and is used
for out of band signalling.

The legacy switch in the picture is a distribution switch.

Do you have a dhcp server in your network? Even a simple home router would
work here.

R.

**Comment by nMaroulis** [comment]
Hi,
Lets start from the beginning. We have two WTPs, one CPP, one Controller on our network with DHCP Server. The WTPs work fine without the CPP, hence connected with their eth0 directly on the network's switch.On the CPP now,it has its eth0 connected to the switch and gets IP just fine, when running the lvnf agent, the controller sees the CPP normally and it is therefore connected. The problem starts when we connect the WTPs to the CPP (both WTP eth0 to CPP's eth1 and eth2), as they dont connect to the controller at all. I believe that the problem is on the CPP side regarding the bridge, because when we restart the network on the CPP it says "Ignoring unknown interface allow-ovs=allow-ovs. done. ". The CPP runs on Debian Wheezy 7.11, with openvswitch 2.4.0 and Python 3.6.

**Comment by rriggio** [comment]
could you copy paste the content of /etc/network/interfaces and the output
of ifconfig?

R.

**Comment by nMaroulis** [comment]
The "ifconfig -a" command has the output: 
"""
br0       Link encap:Ethernet  HWaddr 00:00:24:cd:7a:f9  
          BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

eth0      Link encap:Ethernet  HWaddr 00:00:24:cd:7a:f8  
          inet addr:172.16.10.248  Bcast:172.16.10.255  Mask:255.255.255.0
          inet6 addr: fe80::200:24ff:fecd:7af8/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1120 errors:0 dropped:0 overruns:0 frame:0
          TX packets:451 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:108099 (105.5 KiB)  TX bytes:56649 (55.3 KiB)
          Interrupt:11 Base address:0xe100 

eth1      Link encap:Ethernet  HWaddr 00:00:24:cd:7a:f9  
          BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
          Interrupt:5 Base address:0xe200 

eth2      Link encap:Ethernet  HWaddr 00:00:24:cd:7a:fa  
          BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
          Interrupt:9 Base address:0xe300 

eth3      Link encap:Ethernet  HWaddr 00:00:24:cd:7a:fb  
          BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
          Interrupt:12 Base address:0xe400 

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:16436  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

ovs-system Link encap:Ethernet  HWaddr 22:b7:a3:2a:3d:8d  
          BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

wlan0     Link encap:Ethernet  HWaddr 00:1b:b1:04:56:d6  
          BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
"""
, the "ifconfig" command only shows the lo and eth0 interfaces, the "ifconfig br0 up" etc works but nothing really changes. The interfaces file is exactly the same as your CPP wiki. (Our soekris also has 4 ethernet ports)

**Comment by rriggio** [comment]
strange, it seems that the other interfaces are not brought up at boot and
then maybe for this reason they cannot be added to the OVS.

There should be a command in the ovs CLI suite for listing the ports
attached to a bridge, it should be somthing like:

ovs-ofctl show br0

Could you check it?

R.

**Comment by nMaroulis** [comment]
the output of "ovs-ofctl show br0" is: 
"""
OFPT_FEATURES_REPLY (xid=0x2): dpid:0000000024cd7af9
n_tables:254, n_buffers:256
capabilities: FLOW_STATS TABLE_STATS PORT_STATS QUEUE_STATS ARP_MATCH_IP
actions: output enqueue set_vlan_vid set_vlan_pcp strip_vlan mod_dl_src mod_dl_dst mod_nw_src mod_nw_dst mod_nw_tos mod_tp_src mod_tp_dst
 1(eth1): addr:00:00:24:cd:7a:f9
     config:     0
     state:      0
     current:    100MB-FD AUTO_NEG
     advertised: 10MB-HD 10MB-FD 100MB-HD 100MB-FD COPPER AUTO_NEG AUTO_PAUSE
     supported:  10MB-HD 10MB-FD 100MB-HD 100MB-FD COPPER AUTO_NEG
     speed: 100 Mbps now, 100 Mbps max
 2(eth2): addr:00:00:24:cd:7a:fa
     config:     PORT_DOWN
     state:      LINK_DOWN
     current:    10MB-HD AUTO_NEG
     advertised: 10MB-HD 10MB-FD 100MB-HD 100MB-FD COPPER AUTO_NEG AUTO_PAUSE
     supported:  10MB-HD 10MB-FD 100MB-HD 100MB-FD COPPER AUTO_NEG
     speed: 10 Mbps now, 100 Mbps max
 3(eth3): addr:00:00:24:cd:7a:fb
     config:     PORT_DOWN
     state:      LINK_DOWN
     current:    10MB-HD AUTO_NEG
     advertised: 10MB-HD 10MB-FD 100MB-HD 100MB-FD COPPER AUTO_NEG AUTO_PAUSE
     supported:  10MB-HD 10MB-FD 100MB-HD 100MB-FD COPPER AUTO_NEG
     speed: 10 Mbps now, 100 Mbps max
 LOCAL(br0): addr:00:00:24:cd:7a:f9
     config:     0
     state:      0
     speed: 0 Mbps now, 0 Mbps max
OFPT_GET_CONFIG_REPLY (xid=0x4): frags=normal miss_send_len=0
"""
, so i guess the ports are attached to the bridge. Could it be the WTP's fault for not connecting? In order to connect to the controller via a CPP, do I need to change anything in the /etc/config/files of the WTP?
