### ISSUE TITLE
Some clarification on Lvnfs

### ISSUE THREAD

**Issue by nMaroulis** [5g-empower/empower-lvnf-agent#4]
From my understanding, Lvnfs are click scripts that are loaded on a CPP and perform certain actions. That's where it gets a little incomprehensible, as how these click scripts are loaded on the CPP and where do they exist? Also, what's the connection of lvnfs and LVAPs (as seen in /core/lvnf.py)? I hope you can give me a little help on that.
Thanks

**Comment by rriggio** [comment]
Yes LVNF are click scripts. In this [1] paper e introduce the basic
concepts. Soon I will
create a few pages on the wiki in order to better explain this part (we are
fixing some bugs
in the controller code).

Basically, click scripts are pushed by the controller to the CPP. These are
PC running OVS
and with click installed. The empower-lvnf-agent will receive this
commands, instantiate
the click scripts and connect them to the OVS. Then it is possible to route
traffic across
the LVNF.

The LVAP is basically and LVNF with radio capabilities (LVAPs are also
implemented using click).


[1] http://ieeexplore.ieee.org/document/7502837/

**Comment by nMaroulis** [comment]
I've read and understood the theory, I've had some engagement with the LVAP Agent in the past so i'm  familiar with click etc. but i'm still a little confused about the practical side. By this I mean 1) where do I write the click script in order to load it to the CPP?,  2) How do I load it on the CPP? and 3) Do I need to install something else on the CPP besides what's written in the wiki?.  After loading the scylla component the only thing I see in the index html is a monitor.

**Comment by rriggio** [comment]
There is a REST API and a python API for adding, migrating and chaining the
LVNFs. I will soon add a few pages
on this topic in the wiki. Basically we are finishing the interface between
empower and ryu before publishing those
tutorials

R.
